<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        foreach (['user', 'mata_kuliah'] as $tableName) {
            if (Schema::getColumnType($tableName, 'id') === 'uuid') {
                continue;
            }

            Schema::table($tableName, function (Blueprint $table) {
                $table->dropPrimary();
            });

            DB::statement('ALTER TABLE "'.$tableName.'" ALTER COLUMN "id" DROP DEFAULT');
            DB::statement('ALTER TABLE "'.$tableName.'" ALTER COLUMN "id" TYPE UUID USING gen_random_uuid()');

            Schema::table($tableName, function (Blueprint $table) {
                $table->primary('id');
            });
        }
    }

    public function down(): void
    {
        foreach (['user', 'mata_kuliah'] as $tableName) {
            if (Schema::getColumnType($tableName, 'id') !== 'uuid') {
                continue;
            }

            Schema::table($tableName, function (Blueprint $table) {
                $table->dropPrimary();
            });

            DB::statement('ALTER TABLE "'.$tableName.'" ADD COLUMN "replacement_id" BIGINT GENERATED BY DEFAULT AS IDENTITY');
            DB::statement('ALTER TABLE "'.$tableName.'" DROP COLUMN "id"');
            DB::statement('ALTER TABLE "'.$tableName.'" RENAME COLUMN "replacement_id" TO "id"');

            Schema::table($tableName, function (Blueprint $table) {
                $table->primary('id');
            });
        }
    }
};
